client_id = "de5a97afdffc7c57399e106356013013"
name = "Custom Sticker App"
application_url = "https://sticker-designer-shpify-app.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products,write_app_proxy,read_orders,write_draft_orders"

[app_proxy]
url = "/apps/proxy"
prefix = "apps"
subpath = "custom-stickers"

[auth]
redirect_urls = [
  "https://sticker-designer-shpify-app.vercel.app/auth/callback",
  "https://sticker-designer-shpify-app.vercel.app/auth/shopify/callback",
  "https://sticker-designer-shpify-app.vercel.app/api/auth/callback"
]